// Property 16 — Preservation.
//
// F (current code) and F' (fixed code) cannot both be loaded in one Worker
// isolate, so `ASSERT F(X) = F'(X)` cannot be evaluated live. Observational
// equality is therefore captured as a RECORDED EXPECTATION FIXTURE: this file
// runs a request corpus, snapshots the observable tuple defined by design.md's
// *Preservation Checking* section, and writes it to
// test/__fixtures__/preservation-baseline.json.
//
// MODES
//   (default)          assert  — the corpus must reproduce the committed
//                               fixture byte-for-byte. Any diff is a
//                               preservation regression.
//   PRESERVE=record    record  — rewrite the fixture from the current tree.
//                               See vitest.config.ts; record mode also narrows
//                               the run to this file so no view snapshot is
//                               regenerated by accident (see task 7).
//
// The fixture was recorded against the UNFIXED tree. Tasks 4.5, 5.7 and 6.12
// re-run it in assert mode after each fix.
import { SELF, env } from "cloudflare:test";
import { describe, it, expect } from "vitest";
import fc from "fast-check";
import { nextIp, observe, resetIpCounter, ttlWindowSec } from "./helpers.js";

const APEX = "https://0g.hk";

// Pinned so the fixture is reproducible. Changing either value rewrites the
// generated half of the corpus and MUST be a deliberate, reviewed act.
const FC_SEED = 20260817;
const FC_NUM_RUNS = 10;

const FIXTURE = "./__fixtures__/preservation-baseline.json";

// What the fixture deliberately does not pin down, and why. Recorded inside the
// fixture so the file is self-describing: an over-normalized fixture proves
// nothing, so every entry here has to justify itself.
const NORMALIZATION = {
  "meta.k": "EXCLUDED. Does not exist in F; task 5 adds it. design.md's tuple excludes it explicitly.",
  "meta.h": "Replaced with <token-hash>. Derived from a random per-note edit token.",
  "meta.ct": "Replaced with <ms>. Wall-clock creation time.",
  "x-created-at / x-expires-at / json createdAt / expiresAt / at / until / exp":
    "Replaced with <iso> / <ms>. Wall-clock. The TTL *window* is preserved separately as ttlWindowSec, and 'each edit resets the expiry window' is preserved as metaCtChanged, so 3.4's semantics stay observable without recording clock noise.",
  "x-edit-token / json editToken":
    "Replaced with <token>. Random per note. Presence is still pinned, and tokenAppearsIn records the exact set of places the raw token value occurs — which is what D1 must not widen.",
  "x-edit-url / json editUrl": "Replaced with <url-with-token>: the URL embeds the random token.",
  "set-cookie": "Value replaced with <value>: the admin session token is HMAC-over-now.",
  "server-allocated note names": "Replaced with <random> for the one create that omits `name`.",
  "/admin/stats day keys": "Relabelled day0..day6, newest first: they are today's date, and Promise.all completion order makes the raw key order unstable.",
  "/admin/stats rejection counts":
    "Replaced with <count>. These counts are exactly what D2 changes (a lost telemetry write is the defect), so recording them would encode the bug as an expectation. Shape, status and code set are still pinned; the numbers are Property 4/6's job.",
  "static asset bodies (/llms.txt, /robots.txt, apex manual)":
    "Bytes not recorded; only status, content-type and marker presence. Task 8 edits these files on purpose, and a documentation edit must not read as a preservation regression.",
  "response bodies over 512 chars": "Truncated with a …<truncated> suffix; byteLength is recorded alongside.",
  "HTML bodies": "Recorded as <title> plus a fixed marker table (which branch answered), not as full HTML — test/__snapshots__/views.test.ts.snap owns the markup.",
};

const NOT_EXERCISED = {
  unsafe_target: "Unreachable in the test environment: checkSafeBrowsing() no-ops without SAFE_BROWSING_KEY.",
  content_blocked: "Unreachable in the test environment: env.AI.run throws ('Binding AI needs to be run remotely') and aiModerate fails open.",
  bad_scheme:
    "Unreachable through the public API in F, for any input: hasDangerousScheme() is only consulted when isUrl() is true, and every javascript:/data:/vbscript:/file: string fails URL_NO_SCHEME_RE, while an isUrl()-true string is always normalized to http(s). The two gate-bad-scheme-* entries record what F ACTUALLY does with those inputs (creates a text note) so a fix that changes it shows up. Not fixed here — out of scope.",
};

type Json = Record<string, any>;

const entries: Record<string, any> = {};

async function record(id: string, fn: () => Promise<any>): Promise<void> {
  if (id in entries) throw new Error("duplicate corpus id: " + id);
  entries[id] = await fn();
}

function jsonHeaders(ip: string, extra: Record<string, string> = {}): Record<string, string> {
  return { "content-type": "application/json", accept: "application/json", "cf-connecting-ip": ip, ...extra };
}

async function createJson(body: Json, extra: Record<string, string> = {}): Promise<Response> {
  return SELF.fetch(`${APEX}/`, {
    method: "POST",
    headers: jsonHeaders(nextIp(), extra),
    body: JSON.stringify(body),
    redirect: "manual",
  });
}

async function seedNote(name: string, content: string, ttl?: string): Promise<string> {
  const res = await createJson({ name, content, ...(ttl ? { ttl } : {}) });
  const j: any = await res.json();
  if (!j.editToken) throw new Error(`seed failed for ${name}: ${JSON.stringify(j)}`);
  return j.editToken as string;
}

async function editJson(name: string, body: Json, extra: Record<string, string> = {}, method = "POST"): Promise<Response> {
  return SELF.fetch(`https://${name}.0g.hk/`, {
    method,
    headers: jsonHeaders(nextIp(), extra),
    body: JSON.stringify(body),
    redirect: "manual",
  });
}

async function get(url: string, headers: Record<string, string> = {}): Promise<Response> {
  return SELF.fetch(url, { headers: { "cf-connecting-ip": nextIp(), ...headers }, redirect: "manual" });
}

async function metaCt(name: string): Promise<number | null> {
  const raw = await env.NOTES.get("m:" + name);
  if (!raw) return null;
  try {
    return JSON.parse(raw).ct ?? null;
  } catch {
    return null;
  }
}

/**
 * Fill an IP's rate-limit bucket for this minute AND the next, so a minute
 * rollover between seeding and the request cannot turn a 429 into a 200.
 */
async function saturateRateLimit(ip: string): Promise<void> {
  const minute = Math.floor(Date.now() / 60000);
  await env.NOTES.put(`rl:${ip}:${minute}`, "999", { expirationTtl: 70 });
  await env.NOTES.put(`rl:${ip}:${minute + 1}`, "999", { expirationTtl: 130 });
}

/** An edit observation: the tuple plus the two derived, clock-free TTL facts. */
async function observeEdit(res: Response, name: string, token: string, ctBefore: number | null): Promise<any> {
  const window = ttlWindowSec(res);
  const obs = await observe(res, env, name, { token });
  obs.ttlWindowSec = window;
  obs.metaCtChanged = (await metaCt(name)) !== ctBefore;
  return obs;
}

// Generated half of the corpus: contents that straddle URL_NO_SCHEME_RE, so
// the read-branch selection is exercised across the boundary rather than only
// on hand-picked happy paths.
const arbGenCase = fc.record({
  content: fc.constantFrom(
    "example.com",
    "sub.example.com:8080/path?a=b",
    "example.com/a b",
    "trailing.dot.",
    "github.com/catoncat/0g-hk",
    "https://github.com/catoncat/0g-hk#frag",
    "xn--fsq.com/x",
    "1.2.3.4",
    "a.b",
    "hello world",
    "plain",
    "# md heading\n\nbody text",
  ),
  ttl: fc.constantFrom("1h", "1d", "7d", ""),
});

describe("Property 16: Preservation — recorded baseline", () => {
  it(
    "records the observable tuple for the whole request corpus",
    { timeout: 120_000 },
    async () => {
      resetIpCounter();

      // ---------------------------------------------------------------
      // Case 1 — read path (3.1, 3.2, 3.3, 3.10, 3.11)
      // ---------------------------------------------------------------
      const ALLOWLISTED = "https://github.com/catoncat/0g-hk";
      const EXTERNAL = "https://untrusted.example/path?x=1";

      await seedNote("pbredir", ALLOWLISTED);
      await seedNote("pbext", EXTERNAL);
      await seedNote("pbtext", "hello **bold** preservation");
      await seedNote("pbeditpage", "editable content");
      await seedNote("pbdisabled", "disabled content");
      await env.NOTES.put("d:pbdisabled", JSON.stringify({ reason: "admin", at: Date.now() }), { expirationTtl: 3600 });

      await record("read-302-allowlist", async () =>
        observe(await get("https://pbredir.0g.hk/", { accept: "text/html" }), env, "pbredir"),
      );
      await record("read-302-allowlist-json", async () =>
        observe(await get("https://pbredir.0g.hk/?format=json"), env, "pbredir"),
      );
      await record("read-interstitial", async () =>
        observe(await get("https://pbext.0g.hk/", { accept: "text/html" }), env, "pbext"),
      );
      await record("read-interstitial-go1-does-not-bypass", async () =>
        observe(await get("https://pbext.0g.hk/?go=1", { accept: "text/html" }), env, "pbext"),
      );
      await record("read-interstitial-json", async () =>
        observe(await get("https://pbext.0g.hk/?format=json"), env, "pbext"),
      );
      await record("read-text-notepage", async () =>
        observe(await get("https://pbtext.0g.hk/", { accept: "text/html" }), env, "pbtext"),
      );
      await record("read-text-plain-accept", async () =>
        observe(await get("https://pbtext.0g.hk/", { accept: "text/plain" }), env, "pbtext"),
      );
      await record("read-raw", async () => observe(await get("https://pbtext.0g.hk/raw"), env, "pbtext"));
      await record("read-json-shape", async () =>
        observe(await get("https://pbtext.0g.hk/?format=json"), env, "pbtext"),
      );
      await record("read-404-json", async () =>
        observe(await get("https://pbmissing.0g.hk/", { accept: "application/json" }), env, "pbmissing", {
          skipRaw: true,
        }),
      );
      await record("read-404-html", async () =>
        observe(await get("https://pbmissing.0g.hk/", { accept: "text/html" }), env, null),
      );
      await record("read-410-disabled-json", async () =>
        observe(await get("https://pbdisabled.0g.hk/", { accept: "application/json" }), env, "pbdisabled", {
          skipRaw: true,
          extraKeys: ["d:pbdisabled"],
        }),
      );
      await record("read-410-disabled-html", async () =>
        observe(await get("https://pbdisabled.0g.hk/", { accept: "text/html" }), env, null),
      );
      await record("read-edit-page", async () =>
        observe(await get("https://pbeditpage.0g.hk/edit", { accept: "text/html" }), env, null),
      );
      await record("read-edit-page-missing-note", async () =>
        observe(await get("https://pbmissing.0g.hk/edit", { accept: "text/html" }), env, null),
      );
      await record("read-reserved-subdomain-json", async () =>
        observe(await get("https://admin.0g.hk/", { accept: "application/json" }), env, null),
      );
      await record("exists-free", async () => observe(await get(`${APEX}/exists?n=pbfreename`), env, null));
      await record("exists-brand", async () => observe(await get(`${APEX}/exists?n=paypal`), env, null));
      await record("exists-reserved", async () => observe(await get(`${APEX}/exists?n=admin`), env, null));
      await record("exists-taken", async () => observe(await get(`${APEX}/exists?n=pbtext`), env, null));
      await record("exists-empty", async () => observe(await get(`${APEX}/exists?n=`), env, null));

      // Generated read-path coverage across the URL_NO_SCHEME_RE boundary.
      const genCases = fc.sample(arbGenCase, { numRuns: FC_NUM_RUNS, seed: FC_SEED });
      for (let i = 0; i < genCases.length; i++) {
        const c = genCases[i];
        const name = `gen${i}`;
        await record(`gen-create-${i}`, async () => {
          const res = await createJson({ name, content: c.content, ...(c.ttl ? { ttl: c.ttl } : {}) });
          const obs = await observe(res, env, name);
          obs.input = c;
          return obs;
        });
        await record(`gen-read-${i}`, async () =>
          observe(await get(`https://${name}.0g.hk/`, { accept: "text/html" }), env, name),
        );
      }

      // ---------------------------------------------------------------
      // Case 2 — body-token edits (3.4, 3.5)
      // ---------------------------------------------------------------
      const combos: Array<[string, Json]> = [
        ["edit-body-content-only", { content: "edited body content" }],
        ["edit-body-ttl-only", { ttl: "1d" }],
        ["edit-body-renew-only", { renew: true }],
        ["edit-body-content-and-ttl", { content: "edited with ttl", ttl: "1h" }],
        ["edit-body-content-and-renew", { content: "edited with renew", renew: "1" }],
        ["edit-body-ttl-and-renew", { ttl: "7d", renew: true }],
        ["edit-body-token-only-noop", {}],
        ["edit-body-content-to-url", { content: ALLOWLISTED }],
      ];
      for (let i = 0; i < combos.length; i++) {
        const [id, patch] = combos[i];
        const name = `pbedit${i}`;
        const token = await seedNote(name, "original content", "1h");
        const ctBefore = await metaCt(name);
        await record(id, async () => observeEdit(await editJson(name, { token, ...patch }), name, token, ctBefore));
      }

      await record("edit-put-method", async () => {
        const name = "pbeditput";
        const token = await seedNote(name, "original content");
        const ctBefore = await metaCt(name);
        return observeEdit(await editJson(name, { token, content: "put content" }, {}, "PUT"), name, token, ctBefore);
      });

      await record("edit-form-urlencoded-body", async () => {
        const name = "pbeditform";
        const token = await seedNote(name, "original content");
        const ctBefore = await metaCt(name);
        const res = await SELF.fetch(`https://${name}.0g.hk/`, {
          method: "POST",
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            accept: "application/json",
            "cf-connecting-ip": nextIp(),
          },
          body: new URLSearchParams({ token, content: "form content", ttl: "1d" }).toString(),
          redirect: "manual",
        });
        return observeEdit(res, name, token, ctBefore);
      });

      await record("edit-html-accept-resultpage", async () => {
        const name = "pbedithtml";
        const token = await seedNote(name, "original content");
        const ctBefore = await metaCt(name);
        const res = await SELF.fetch(`https://${name}.0g.hk/`, {
          method: "POST",
          headers: { "content-type": "application/json", accept: "text/html", "cf-connecting-ip": nextIp() },
          body: JSON.stringify({ token, content: "html accept content" }),
          redirect: "manual",
        });
        return observeEdit(res, name, token, ctBefore);
      });

      // Body-first precedence: a body token AND a different header token must
      // resolve to the body token (design.md rejects header-first for exactly
      // this input).
      await record("edit-body-token-wins-over-header-token", async () => {
        const name = "pbeditprec";
        const token = await seedNote(name, "original content");
        const ctBefore = await metaCt(name);
        const res = await editJson(name, { token, content: "body token wins" }, { "x-edit-token": "not-the-token" });
        return observeEdit(res, name, token, ctBefore);
      });

      // F ignores X-Edit-Token entirely, so a GET carrying only the header is a
      // plain read. F' must keep serving a plain read (2.3 / Property 16).
      await record("edit-get-with-header-token-only-is-a-read", async () => {
        const name = "pbeditgethdr";
        const token = await seedNote(name, "unchanged by a GET");
        const ctBefore = await metaCt(name);
        const res = await get(`https://${name}.0g.hk/?format=json`, { "x-edit-token": token });
        return observeEdit(res, name, token, ctBefore);
      });

      // Deprecated ?edit= transport (a C1 input; recorded for RESPONSE-level
      // preservation only — log lines are deliberately not part of the tuple,
      // since redacting them is the whole point of D1).
      await record("deprecated-get-query-edit", async () => {
        const name = "pbdepget";
        const token = await seedNote(name, "original content");
        const ctBefore = await metaCt(name);
        const res = await get(
          `https://${name}.0g.hk/?edit=${encodeURIComponent(token)}&c=${encodeURIComponent("via deprecated GET")}`,
          { accept: "application/json" },
        );
        return observeEdit(res, name, token, ctBefore);
      });
      await record("deprecated-post-query-edit", async () => {
        const name = "pbdeppost";
        const token = await seedNote(name, "original content");
        const ctBefore = await metaCt(name);
        const res = await SELF.fetch(
          `https://${name}.0g.hk/?edit=${encodeURIComponent(token)}&c=${encodeURIComponent("via deprecated POST")}`,
          { method: "POST", headers: { accept: "application/json", "cf-connecting-ip": nextIp() }, redirect: "manual" },
        );
        return observeEdit(res, name, token, ctBefore);
      });

      // ---------------------------------------------------------------
      // Case 3 — error envelopes (3.5, 3.8, 3.9)
      // ---------------------------------------------------------------
      const errToken = await seedNote("pberr", "error envelope target");

      await record("err-missing-token", async () =>
        observe(await editJson("pberr", { content: "x" }), env, "pberr"),
      );
      await record("err-invalid-token", async () =>
        observe(await editJson("pberr", { token: "AAAAAAAAAAAAAAAAAAAAAA", content: "x" }), env, "pberr"),
      );
      await record("err-not-editable-no-meta", async () =>
        observe(await editJson("pbnometa", { token: errToken, content: "x" }), env, "pbnometa", { skipRaw: true }),
      );
      await record("err-corrupt-meta", async () => {
        await env.NOTES.put("n:pbcorrupt", "corrupt meta note");
        await env.NOTES.put("m:pbcorrupt", "{not json");
        return observe(await editJson("pbcorrupt", { token: errToken, content: "x" }), env, "pbcorrupt");
      });
      await record("err-not-found-content-missing", async () => {
        const name = "pbnocontent";
        const token = await seedNote(name, "will lose its content");
        await env.NOTES.delete("n:" + name);
        return observe(await editJson(name, { token, ttl: "1d" }), env, name, { skipRaw: true });
      });
      await record("err-invalid-ttl-create", async () =>
        observe(await createJson({ name: "pbttlbad", content: "x", ttl: "9d" }), env, null),
      );
      await record("err-invalid-ttl-create-html", async () =>
        observe(
          await SELF.fetch(`${APEX}/`, {
            method: "POST",
            headers: { "content-type": "application/json", accept: "text/html", "cf-connecting-ip": nextIp() },
            body: JSON.stringify({ name: "pbttlbad2", content: "x", ttl: "9d" }),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("err-invalid-ttl-edit", async () =>
        observe(await editJson("pberr", { token: errToken, ttl: "9d" }), env, "pberr"),
      );
      await record("err-invalid-name", async () =>
        observe(await createJson({ name: "-bad-name", content: "x" }), env, null),
      );
      await record("err-reserved-name", async () =>
        observe(await createJson({ name: "admin", content: "x" }), env, null),
      );
      await record("err-name-taken-json", async () =>
        observe(await createJson({ name: "pbtext", content: "different content" }), env, null),
      );
      await record("err-name-taken-html", async () =>
        observe(
          await SELF.fetch(`${APEX}/`, {
            method: "POST",
            headers: { "content-type": "application/json", accept: "text/html", "cf-connecting-ip": nextIp() },
            body: JSON.stringify({ name: "pbtext", content: "different content" }),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("err-url-too-long", async () =>
        observe(await createJson({ name: "pburllong", content: "https://ex.com/" + "a".repeat(2100) }), env, null),
      );
      await record("err-text-too-long", async () =>
        observe(await createJson({ name: "pbtextlong", content: "x".repeat(24 * 1024 + 1) }), env, null),
      );
      await record("err-malformed-url", async () =>
        observe(await createJson({ name: "pbmalformed", content: "http://" }), env, null),
      );
      await record("err-missing-content-json", async () => observe(await createJson({ name: "pbnoc" }), env, null));
      await record("err-missing-content-html-editor", async () =>
        observe(
          await SELF.fetch(`${APEX}/`, {
            method: "POST",
            headers: { "content-type": "application/json", accept: "text/html", "cf-connecting-ip": nextIp() },
            body: JSON.stringify({}),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("err-bad-body", async () =>
        observe(
          await SELF.fetch(`${APEX}/`, {
            method: "POST",
            headers: jsonHeaders(nextIp()),
            body: "{not json",
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("err-rate-limited-create", async () => {
        const ip = nextIp();
        await saturateRateLimit(ip);
        const res = await SELF.fetch(`${APEX}/`, {
          method: "POST",
          headers: jsonHeaders(ip),
          body: JSON.stringify({ name: "pbratelimited", content: "x" }),
          redirect: "manual",
        });
        return observe(res, env, null);
      });
      await record("err-rate-limited-edit", async () => {
        const ip = nextIp();
        await saturateRateLimit(ip);
        const res = await SELF.fetch("https://pberr.0g.hk/", {
          method: "POST",
          headers: jsonHeaders(ip),
          body: JSON.stringify({ token: errToken, content: "rate limited" }),
          redirect: "manual",
        });
        return observe(res, env, "pberr");
      });

      // Gates. Each uses its own address, so no sequence accumulates the 5
      // rejections that would tighten the adaptive cap.
      await record("gate-brand-blocked", async () =>
        observe(await createJson({ name: "mypaypal", content: "x" }), env, null),
      );
      await record("gate-shortener-blocked", async () =>
        observe(await createJson({ name: "pbshort", content: "https://bit.ly/abc" }), env, null),
      );
      await record("gate-order-brand-before-shortener", async () =>
        observe(await createJson({ name: "mypaypal2", content: "https://bit.ly/abc" }), env, null),
      );
      await record("gate-order-ratelimit-before-brand", async () => {
        const ip = nextIp();
        await saturateRateLimit(ip);
        const res = await SELF.fetch(`${APEX}/`, {
          method: "POST",
          headers: jsonHeaders(ip),
          body: JSON.stringify({ name: "mypaypal3", content: "x" }),
          redirect: "manual",
        });
        return observe(res, env, null);
      });
      await record("gate-shortener-blocked-on-edit", async () => {
        const name = "pbshortedit";
        const token = await seedNote(name, "original content");
        return observe(await editJson(name, { token, content: "https://bit.ly/xyz" }), env, name);
      });
      // See NOT_EXERCISED.bad_scheme: these record what F actually does.
      await record("gate-bad-scheme-javascript-unreachable", async () =>
        observe(await createJson({ name: "pbjsscheme", content: "javascript:alert(1)" }), env, "pbjsscheme"),
      );
      await record("gate-bad-scheme-data-unreachable", async () =>
        observe(await createJson({ name: "pbdatascheme", content: "data:text/html,x" }), env, "pbdatascheme"),
      );

      // ---------------------------------------------------------------
      // Case 4 — create success (3.6)
      // ---------------------------------------------------------------
      await record("create-json-201-text", async () => {
        const res = await createJson({ name: "pbc1", content: "created text note", ttl: "7d" });
        const token = res.headers.get("x-edit-token") || "";
        const window = ttlWindowSec(res);
        const obs = await observe(res, env, "pbc1", { token });
        obs.ttlWindowSec = window;
        return obs;
      });
      await record("create-json-201-url-allowlisted", async () => {
        const res = await createJson({ name: "pbc2", content: ALLOWLISTED });
        const token = res.headers.get("x-edit-token") || "";
        return observe(res, env, "pbc2", { token });
      });
      await record("create-json-201-ttl-1h", async () => {
        const res = await createJson({ name: "pbc3", content: "one hour note", ttl: "1h" });
        const window = ttlWindowSec(res);
        const obs = await observe(res, env, "pbc3", { token: res.headers.get("x-edit-token") || "" });
        obs.ttlWindowSec = window;
        return obs;
      });
      await record("create-json-201-ttl-1d", async () => {
        const res = await createJson({ name: "pbc4", content: "one day note", ttl: "1d" });
        const window = ttlWindowSec(res);
        const obs = await observe(res, env, "pbc4", { token: res.headers.get("x-edit-token") || "" });
        obs.ttlWindowSec = window;
        return obs;
      });
      await record("create-html-resultpage", async () => {
        const res = await SELF.fetch(`${APEX}/`, {
          method: "POST",
          headers: { "content-type": "application/json", accept: "text/html", "cf-connecting-ip": nextIp() },
          body: JSON.stringify({ name: "pbc5", content: "result page note" }),
          redirect: "manual",
        });
        return observe(res, env, "pbc5", { token: res.headers.get("x-edit-token") || "" });
      });
      await record("create-get-query-deprecated", async () => {
        const res = await get(`${APEX}/?n=pbc6&c=${encodeURIComponent("created via query")}`, {
          accept: "application/json",
        });
        return observe(res, env, "pbc6", { token: res.headers.get("x-edit-token") || "" });
      });
      await record("create-form-body", async () => {
        const res = await SELF.fetch(`${APEX}/`, {
          method: "POST",
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            accept: "application/json",
            "cf-connecting-ip": nextIp(),
          },
          body: new URLSearchParams({ n: "pbc7", c: "form created", ttl: "1d" }).toString(),
          redirect: "manual",
        });
        return observe(res, env, "pbc7", { token: res.headers.get("x-edit-token") || "" });
      });
      await record("create-text-plain-body-random-name", async () => {
        const res = await SELF.fetch(`${APEX}/`, {
          method: "POST",
          headers: { "content-type": "text/plain", accept: "application/json", "cf-connecting-ip": nextIp() },
          body: "plain text body, server allocates the name",
          redirect: "manual",
        });
        const clone = res.clone();
        const allocated = (await clone.json<any>()).name as string;
        return observe(res, env, allocated, {
          token: res.headers.get("x-edit-token") || "",
          randomName: allocated,
        });
      });

      // ---------------------------------------------------------------
      // Case 5 — admin (3.13)
      // ---------------------------------------------------------------
      const ADMIN_KEY = "pb-admin-key";
      (env as any).ADMIN_KEY = ADMIN_KEY;
      const adminHeaders = { accept: "application/json", authorization: `Bearer ${ADMIN_KEY}` };

      await record("admin-stats-bearer", async () => observe(await get(`${APEX}/admin/stats`, adminHeaders), env, null));
      await record("admin-stats-key-param", async () =>
        observe(await get(`${APEX}/admin/stats?key=${ADMIN_KEY}`, { accept: "application/json" }), env, null),
      );
      await record("admin-note-detail", async () =>
        observe(await get(`${APEX}/admin/note?name=pbtext`, adminHeaders), env, null),
      );
      await record("admin-note-detail-missing", async () =>
        observe(await get(`${APEX}/admin/note?name=pbmissing`, adminHeaders), env, null),
      );
      await record("admin-note-detail-bad-name", async () =>
        observe(await get(`${APEX}/admin/note?name=-bad-`, adminHeaders), env, null),
      );

      await seedNote("pbadmin", "admin lifecycle note");
      await env.NOTES.put("abuse:pbadmin", "2", { expirationTtl: 3600 });
      await record("admin-disable", async () => {
        const res = await SELF.fetch(`${APEX}/admin/disable?name=pbadmin`, {
          method: "POST",
          headers: adminHeaders,
          redirect: "manual",
        });
        return observe(res, env, "pbadmin", { extraKeys: ["d:pbadmin", "abuse:pbadmin"] });
      });
      await record("admin-disable-then-read-410", async () =>
        observe(await get("https://pbadmin.0g.hk/", { accept: "application/json" }), env, null),
      );
      await record("admin-enable-clears-both-keys", async () => {
        const res = await SELF.fetch(`${APEX}/admin/enable?name=pbadmin`, {
          method: "POST",
          headers: adminHeaders,
          redirect: "manual",
        });
        return observe(res, env, "pbadmin", { extraKeys: ["d:pbadmin", "abuse:pbadmin"] });
      });
      await record("admin-enable-then-read-200", async () =>
        observe(await get("https://pbadmin.0g.hk/?format=json"), env, "pbadmin"),
      );
      await record("admin-delete", async () => {
        const res = await SELF.fetch(`${APEX}/admin/delete?name=pbadmin`, {
          method: "POST",
          headers: adminHeaders,
          redirect: "manual",
        });
        return observe(res, env, "pbadmin", { skipRaw: true, extraKeys: ["d:pbadmin", "abuse:pbadmin"] });
      });
      await record("admin-delete-then-read-404", async () =>
        observe(await get("https://pbadmin.0g.hk/", { accept: "application/json" }), env, null),
      );
      await record("admin-config-get", async () => observe(await get(`${APEX}/admin/config`, adminHeaders), env, null));
      await record("admin-config-post", async () =>
        observe(
          await SELF.fetch(`${APEX}/admin/config`, {
            method: "POST",
            headers: { ...adminHeaders, "content-type": "application/json" },
            body: JSON.stringify({ textMax: 20480 }),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("admin-config-post-invalid", async () =>
        observe(
          await SELF.fetch(`${APEX}/admin/config`, {
            method: "POST",
            headers: { ...adminHeaders, "content-type": "application/json" },
            body: JSON.stringify({ textMax: 1 }),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("admin-config-post-reset", async () =>
        observe(
          await SELF.fetch(`${APEX}/admin/config`, {
            method: "POST",
            headers: { ...adminHeaders, "content-type": "application/json" },
            body: JSON.stringify({ reset: true }),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("admin-unauthorized-bad-key", async () =>
        observe(await get(`${APEX}/admin/stats?key=wrong-key`, { accept: "application/json" }), env, null),
      );

      // Session login flow (HTML surface).
      await record("admin-login-page", async () => observe(await get(`${APEX}/admin`, { accept: "text/html" }), env, null));
      let sessionCookie = "";
      await record("admin-login-post", async () => {
        const res = await SELF.fetch(`${APEX}/admin/login`, {
          method: "POST",
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            origin: `https://0g.hk`,
            "cf-connecting-ip": nextIp(),
          },
          body: new URLSearchParams({ password: ADMIN_KEY }).toString(),
          redirect: "manual",
        });
        const setCookie = res.headers.get("set-cookie") || "";
        sessionCookie = setCookie.split(";")[0];
        return observe(res, env, null);
      });
      await record("admin-dashboard-with-session", async () =>
        observe(await get(`${APEX}/admin/dashboard`, { accept: "text/html", cookie: sessionCookie }), env, null),
      );
      await record("admin-dashboard-without-session", async () =>
        observe(await get(`${APEX}/admin/dashboard`, { accept: "text/html" }), env, null),
      );
      await record("admin-logout", async () =>
        observe(
          await SELF.fetch(`${APEX}/admin/logout`, {
            method: "POST",
            headers: { origin: `https://0g.hk`, cookie: sessionCookie, "cf-connecting-ip": nextIp() },
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("admin-login-post-wrong-password", async () =>
        observe(
          await SELF.fetch(`${APEX}/admin/login`, {
            method: "POST",
            headers: {
              "content-type": "application/x-www-form-urlencoded",
              origin: `https://0g.hk`,
              "cf-connecting-ip": nextIp(),
            },
            body: new URLSearchParams({ password: "wrong" }).toString(),
            redirect: "manual",
          }),
          env,
          null,
        ),
      );
      await record("admin-not-configured", async () => {
        delete (env as any).ADMIN_KEY;
        const obs = await observe(await get(`${APEX}/admin/stats?key=anything`, { accept: "application/json" }), env, null);
        (env as any).ADMIN_KEY = ADMIN_KEY;
        return obs;
      });

      // ---------------------------------------------------------------
      // Case 6 — CORS, assets, apex manual, abuse report (3.12, 3.14, 3.15)
      // ---------------------------------------------------------------
      for (const [id, url] of [
        ["options-apex-root", `${APEX}/`],
        ["options-apex-exists", `${APEX}/exists?n=x`],
        ["options-admin", `${APEX}/admin/stats`],
        ["options-subdomain-root", "https://pbtext.0g.hk/"],
        ["options-subdomain-raw", "https://pbtext.0g.hk/raw"],
        ["options-unknown-host", "https://example.com/"],
      ] as Array<[string, string]>) {
        await record(id, async () =>
          observe(
            await SELF.fetch(url, { method: "OPTIONS", headers: { "cf-connecting-ip": nextIp() }, redirect: "manual" }),
            env,
            null,
          ),
        );
      }

      await record("assets-llms-txt", async () =>
        observe(await env.ASSETS.fetch("https://0g.hk/llms.txt"), env, null, { textMarkers: ["0g.hk"] }),
      );
      await record("assets-robots-txt", async () =>
        observe(await env.ASSETS.fetch("https://0g.hk/robots.txt"), env, null, {
          textMarkers: ["Allow: /llms.txt", "User-agent:"],
        }),
      );
      await record("apex-manual-for-non-browser", async () =>
        observe(await get(`${APEX}/`, { accept: "*/*", "user-agent": "curl/8.0" }), env, null, {
          textMarkers: ["0g.hk"],
        }),
      );
      await record("apex-editor-for-browser", async () =>
        observe(await get(`${APEX}/`, { accept: "text/html", "user-agent": "Mozilla/5.0" }), env, null),
      );
      await record("apex-unknown-path-json", async () =>
        observe(await get(`${APEX}/nope`, { accept: "application/json" }), env, null),
      );
      await record("apex-unknown-path-html", async () =>
        observe(await get(`${APEX}/nope`, { accept: "text/html" }), env, null),
      );
      await record("unknown-host-json", async () =>
        observe(await get("https://example.com/", { accept: "application/json" }), env, null),
      );

      // Abuse reporting: single report, same-reporter dedupe, HTML surface.
      // TURNSTILE_SECRET is unset here, so verifyTurnstile() no-ops both before
      // and after the fix (2.13) — these are preservation inputs, not C3 inputs.
      await seedNote("pbabuse", EXTERNAL);
      const reporterIp = "203.0.113.7";
      await record("abuse-report-first", async () =>
        observe(
          await SELF.fetch("https://pbabuse.0g.hk/abuse/report", {
            method: "POST",
            headers: { accept: "application/json", "cf-connecting-ip": reporterIp },
            redirect: "manual",
          }),
          env,
          "pbabuse",
          { extraKeys: ["abuse:pbabuse", "d:pbabuse"] },
        ),
      );
      await record("abuse-report-same-reporter-deduped", async () =>
        observe(
          await SELF.fetch("https://pbabuse.0g.hk/abuse/report", {
            method: "POST",
            headers: { accept: "application/json", "cf-connecting-ip": reporterIp },
            redirect: "manual",
          }),
          env,
          "pbabuse",
          { extraKeys: ["abuse:pbabuse", "d:pbabuse"] },
        ),
      );
      await record("abuse-report-html-surface", async () =>
        observe(
          await SELF.fetch("https://pbabuse.0g.hk/abuse/report", {
            method: "POST",
            headers: { accept: "text/html", "cf-connecting-ip": reporterIp },
            redirect: "manual",
          }),
          env,
          null,
        ),
      );

      // ---------------------------------------------------------------
      // Fixture
      // ---------------------------------------------------------------
      const doc = {
        $comment:
          "RECORDED AGAINST THE UNFIXED TREE (Property 16 baseline). Assert mode is the default; " +
          "PRESERVE=record rewrites this file. Do not hand-edit.",
        fastCheck: { seed: FC_SEED, numRuns: FC_NUM_RUNS },
        tuple: [
          "status",
          "JSON error code",
          "x-* headers (sorted)",
          "location",
          "/raw bytes",
          "n:<name> and m:<name> KV state, excluding meta.k",
        ],
        normalization: NORMALIZATION,
        notExercised: NOT_EXERCISED,
        entryCount: Object.keys(entries).length,
        entries,
      };
      await expect(JSON.stringify(doc, null, 2) + "\n").toMatchFileSnapshot(FIXTURE);
    },
  );
});
