// Admin panel: session-based web UI + Bearer-auth JSON API.
// Secrets: ADMIN_KEY (required), ADMIN_SESSION_SECRET (optional, falls back to ADMIN_KEY).
import { NAME_RE, REJECT_CODES, BASE_HOST } from "./constants.js";
import { ctEq, esc, isUrl, normalizeName } from "./util.js";
import { html, jsonResponse, jsonError, COMMON_CSS, footerHtml, SECURITY_HEADERS, statusPage } from "./responses.js";

const COOKIE_NAME = "admin_session";
const SESSION_TTL_SEC = 2 * 3600;
const COLORS = ["#b02a2a","#8a5a00","#6b6b66","#2f7a3a","#2f5a7a"];

function b64url(b){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
async function hmac(secret,data){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const s=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(data));return b64url(new Uint8Array(s));}
function sessionSecret(env){return (env&&(env.ADMIN_SESSION_SECRET||env.ADMIN_KEY))||"";}
async function makeSession(env){const exp=Math.floor(Date.now()/1000)+SESSION_TTL_SEC;const p="v1."+exp;return p+"."+(await hmac(sessionSecret(env),p));}
async function verifySession(env,val){if(!val)return false;const p=val.split(".");if(p.length!==3)return false;if(p[0]!=="v1")return false;const exp=parseInt(p[1],10);if(!exp||exp*1000<Date.now())return false;return ctEq(p[2],await hmac(sessionSecret(env),p[0]+"."+p[1]));}
function getCookie(req,name){const r=req.headers.get("cookie")||"";for(const seg of r.split(/;\s*/)){const i=seg.indexOf("=");if(i>0&&seg.slice(0,i)===name)return decodeURIComponent(seg.slice(i+1));}return "";}
function setCookieHeader(v,maxAge){const a=[COOKIE_NAME+"="+v,"Path=/","HttpOnly","Secure","SameSite=Strict"];if(maxAge!=null)a.push("Max-Age="+maxAge);return a.join("; ");}
function redirect(path,setCookie){const h=Object.assign({location:path},SECURITY_HEADERS);if(setCookie)h["set-cookie"]=setCookie;return new Response(null,{status:302,headers:h});}

async function statsByDay(env){const days=[];const now=Date.now();for(let i=0;i<7;i++)days.push(new Date(now-i*86400000).toISOString().slice(0,10).replace(/-/g,""));const out={};await Promise.all(days.map(async(d)=>{const row={};await Promise.all(REJECT_CODES.map(async(c)=>{const v=await env.NOTES.get("rej:"+d+":"+c);row[c]=v?parseInt(v,10):0;}));out[d]=row;}));return out;}

async function loadNoteDetail(env,name){const [content,metaRaw,disabledRaw,abuseCount]=await Promise.all([env.NOTES.get("n:"+name),env.NOTES.get("m:"+name),env.NOTES.get("d:"+name),env.NOTES.get("abuse:"+name)]);let meta=null;try{meta=metaRaw?JSON.parse(metaRaw):null;}catch{}let dInfo=null;if(disabledRaw){try{dInfo=JSON.parse(disabledRaw);}catch{dInfo={reason:disabledRaw};}}const kind=content!=null?(isUrl(content)?"url":"text"):null;return{name,exists:content!=null,disabled:!!disabledRaw,disabledReason:(dInfo&&dInfo.reason)||null,disabledAt:dInfo&&dInfo.at?new Date(dInfo.at).toISOString():null,abuseCount:abuseCount?parseInt(abuseCount,10):0,kind,ttl:meta&&meta.t,createdAt:meta&&meta.ct?new Date(meta.ct).toISOString():null,content};}

async function handleJsonApi(req,env,url){const expected=env&&env.ADMIN_KEY;const auth=req.headers.get("authorization")||"";const bearer=auth.startsWith("Bearer ")?auth.slice(7):"";const provided=bearer||url.searchParams.get("key")||"";if(!expected)return jsonError("admin_disabled","Admin API not configured",503);if(!provided||!ctEq(provided,expected))return jsonError("unauthorized","Invalid admin key",401);const path=url.pathname;if(path==="/admin/stats")return jsonResponse({ok:true,days:await statsByDay(env)});const name=normalizeName(url.searchParams.get("name"));if(!name||!NAME_RE.test(name))return jsonError("bad_name","Missing/invalid name",400);if(path==="/admin/note"&&req.method==="GET")return jsonResponse({ok:true,...(await loadNoteDetail(env,name))});if(path==="/admin/disable"&&req.method==="POST"){await env.NOTES.put("d:"+name,JSON.stringify({reason:"admin",at:Date.now()}),{expirationTtl:60*60*24*365});return jsonResponse({ok:true,name,disabled:true});}if(path==="/admin/enable"&&req.method==="POST"){await env.NOTES.delete("d:"+name);await env.NOTES.delete("abuse:"+name);return jsonResponse({ok:true,name,disabled:false});}if(path==="/admin/delete"&&req.method==="POST"){await Promise.all([env.NOTES.delete("n:"+name),env.NOTES.delete("m:"+name),env.NOTES.delete("d:"+name),env.NOTES.delete("abuse:"+name)]);return jsonResponse({ok:true,name,deleted:true});}return jsonError("not_found","Unknown admin endpoint",404);}

const ADMIN_CSS = COMMON_CSS + ".admin-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;gap:8px;flex-wrap:wrap}.admin-head h1{margin:0;font-size:20px}.chart{display:flex;align-items:flex-end;gap:6px;height:140px;padding:4px 0;border-bottom:1px solid var(--border);margin-bottom:6px}.chart .day{flex:1;display:flex;flex-direction:column-reverse;gap:1px;min-width:0}.chart .bar{border-radius:2px 2px 0 0;min-height:1px}.chart-labels{display:flex;gap:6px;color:var(--faint);font-size:11px;font-family:var(--mono)}.chart-labels span{flex:1;text-align:center;min-width:0}.legend{font-size:12px;color:var(--muted);display:flex;gap:12px;flex-wrap:wrap;margin-top:8px}.legend i{display:inline-block;width:10px;height:10px;border-radius:2px;vertical-align:middle;margin-right:4px}table.kv{width:100%;border-collapse:collapse;font-size:13px}table.kv td{padding:6px 8px;border-bottom:1px solid var(--border);vertical-align:top}table.kv td:first-child{color:var(--muted);width:120px}.code{font-family:var(--mono);font-size:12px;background:var(--surface-2);padding:8px 10px;border-radius:6px;word-break:break-all;white-space:pre-wrap;max-height:400px;overflow:auto}.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:11px;font-weight:600}.badge.ok{background:rgba(47,122,58,0.15);color:var(--ok)}.badge.err{background:rgba(176,42,42,0.15);color:var(--err)}.badge.warn{background:var(--warn-bg);color:var(--warn-fg)}";

function adminHtml(title,inner,status){const body='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>'+esc(title)+' · 0g.hk admin</title><style>'+ADMIN_CSS+'</style></head><body><div class="wrap">'+inner+footerHtml()+'</div></body></html>';return html(body,status||200);}

function loginPage(err){const inner='<div class="admin-head"><h1>🔐 0g.hk admin</h1></div><div class="card"><form method="POST" action="/admin/login"><p class="muted" style="margin:0 0 10px">输入 ADMIN_KEY 登录。会话 2 小时。</p>'+(err?'<p class="err">'+esc(err)+'</p>':"")+'<input class="input" type="password" name="password" placeholder="admin key" autofocus required autocomplete="current-password"><div style="margin-top:10px"><button class="btn primary" type="submit">登录</button></div></form></div>';return adminHtml("登录",inner,err?401:200);}

function dashboardPage(stats){const days=Object.keys(stats).sort();let max=1;for(const d of days)for(const c of REJECT_CODES)max=Math.max(max,stats[d][c]||0);const cols=days.map((d)=>{const bars=REJECT_CODES.map((c,i)=>{const v=stats[d][c]||0;const h=v>0?Math.max(2,Math.round((v/max)*100)):0;return '<div class="bar" style="height:'+h+'%;background:'+COLORS[i]+'" title="'+c+': '+v+'"></div>';}).join("");return '<div class="day">'+bars+'</div>';}).join("");const labels=days.map((d)=>'<span>'+d.slice(4,6)+'/'+d.slice(6,8)+'</span>').join("");const legend=REJECT_CODES.map((c,i)=>'<span><i style="background:'+COLORS[i]+'"></i>'+c+'</span>').join("");const totals={};for(const c of REJECT_CODES)totals[c]=days.reduce((a,d)=>a+(stats[d][c]||0),0);const totalAll=Object.values(totals).reduce((a,b)=>a+b,0);const rows=REJECT_CODES.map((c)=>'<tr><td>'+c+'</td><td><strong>'+totals[c]+'</strong></td></tr>').join("");const inner='<div class="admin-head"><h1>🔐 0g.hk admin</h1><div><a href="/admin/dashboard" style="color:var(--muted);font-size:13px">刷新</a> · <form method="POST" action="/admin/logout" style="display:inline"><button class="btn ghost" style="padding:4px 10px;font-size:12px" type="submit">退出</button></form></div></div><div class="card"><h2>近 7 日拦截统计</h2><p class="muted" style="margin:-4px 0 12px">合计 <strong>'+totalAll+'</strong> 次，左旧右新。</p><div class="chart">'+cols+'</div><div class="chart-labels">'+labels+'</div><div class="legend">'+legend+'</div></div><div class="card"><h2>分类合计</h2><table class="kv">'+rows+'</table></div><div class="card"><h2>查看 / 管理某个笔记</h2><form method="GET" action="/admin/note" class="row"><input class="input" name="name" placeholder="子域名 / name" pattern="[a-z0-9]([a-z0-9-]*[a-z0-9])?" required style="max-width:260px"><button class="btn primary" type="submit">查看</button></form></div>';return adminHtml("dashboard",inner);}

function noteDetailPage(d){if(!d.exists&&!d.disabled){const inner='<div class="admin-head"><h1>🔐 '+esc(d.name)+'</h1><a href="/admin/dashboard" style="color:var(--muted);font-size:13px">← 返回</a></div><div class="card"><p>没有找到该笔记（可能已过期或从未创建）。</p></div>';return adminHtml(d.name,inner,404);}const statusBadge=d.disabled?'<span class="badge err">已禁用</span>':'<span class="badge ok">正常</span>';const abuseBadge=d.abuseCount>0?'<span class="badge warn">举报 '+d.abuseCount+'</span>':"";const shortUrl="https://"+d.name+"."+BASE_HOST;const pairs=[["name",esc(d.name)],["short",'<a href="'+shortUrl+'" rel="noopener noreferrer nofollow" target="_blank">'+shortUrl+'</a>'],["status",statusBadge+" "+abuseBadge],["kind",d.kind||"—"],["ttl",d.ttl||"—"],["created",d.createdAt||"—"]];const rows=pairs.map((p)=>'<tr><td>'+p[0]+'</td><td>'+p[1]+'</td></tr>').join("");const actions=[];if(!d.disabled)actions.push('<form method="POST" action="/admin/disable" style="display:inline"><input type="hidden" name="name" value="'+esc(d.name)+'"><button class="btn" type="submit">禁用</button></form>');else actions.push('<form method="POST" action="/admin/enable" style="display:inline"><input type="hidden" name="name" value="'+esc(d.name)+'"><button class="btn" type="submit">解除禁用</button></form>');actions.push('<form method="POST" action="/admin/delete" style="display:inline" onsubmit="return confirm(\'彻底删除 '+esc(d.name)+'？\');"><input type="hidden" name="name" value="'+esc(d.name)+'"><button class="btn" type="submit" style="color:var(--err)">删除</button></form>');const contentSection=d.content!=null?'<div class="card"><h2>内容</h2><div class="code">'+esc(d.content)+'</div></div>':"";const inner='<div class="admin-head"><h1>🔐 '+esc(d.name)+'</h1><a href="/admin/dashboard" style="color:var(--muted);font-size:13px">← 仪表盘</a></div><div class="card"><table class="kv">'+rows+'</table><div class="row" style="margin-top:14px">'+actions.join("")+'</div></div>'+contentSection;return adminHtml(d.name,inner);}

async function handleWebUi(req,env,url){const path=url.pathname;const expected=env&&env.ADMIN_KEY;if(!expected)return statusPage({title:"未配置 ADMIN_KEY",message:"当前未启用管理后台。",detailsHtml:'<p class="muted">请先执行 <code>wrangler secret put ADMIN_KEY</code>。</p>',tone:"warn",status:503,primaryHref:"https://"+BASE_HOST+"/",primaryLabel:"返回首页"});if(path==="/admin"||path==="/admin/"){if(await verifySession(env,getCookie(req,COOKIE_NAME)))return redirect("/admin/dashboard");return loginPage();}if(path==="/admin/login"&&req.method==="POST"){let pwd="";try{const fd=await req.formData();pwd=String(fd.get("password")||"");}catch{}if(!pwd||!ctEq(pwd,expected))return loginPage("密码不正确");return redirect("/admin/dashboard",setCookieHeader(await makeSession(env),SESSION_TTL_SEC));}if(path==="/admin/logout")return redirect("/admin",setCookieHeader("",0));if(!(await verifySession(env,getCookie(req,COOKIE_NAME))))return redirect("/admin");if(path==="/admin/dashboard")return dashboardPage(await statsByDay(env));if(path==="/admin/note"&&req.method==="GET"){const name=normalizeName(url.searchParams.get("name"));if(!name||!NAME_RE.test(name))return redirect("/admin/dashboard");return noteDetailPage(await loadNoteDetail(env,name));}if((path==="/admin/disable"||path==="/admin/enable"||path==="/admin/delete")&&req.method==="POST"){let name="";try{const fd=await req.formData();name=normalizeName(String(fd.get("name")||""));}catch{}if(!name||!NAME_RE.test(name))return redirect("/admin/dashboard");if(path==="/admin/disable")await env.NOTES.put("d:"+name,JSON.stringify({reason:"admin",at:Date.now()}),{expirationTtl:60*60*24*365});else if(path==="/admin/enable"){await env.NOTES.delete("d:"+name);await env.NOTES.delete("abuse:"+name);}else if(path==="/admin/delete")await Promise.all([env.NOTES.delete("n:"+name),env.NOTES.delete("m:"+name),env.NOTES.delete("d:"+name),env.NOTES.delete("abuse:"+name)]);return redirect("/admin/note?name="+encodeURIComponent(name));}return redirect("/admin/dashboard");}

export async function handleAdmin(req,env,url){const auth=req.headers.get("authorization")||"";const isJsonApi=auth.startsWith("Bearer ")||url.searchParams.has("key")||url.searchParams.get("format")==="json";return isJsonApi?handleJsonApi(req,env,url):handleWebUi(req,env,url);}
